S=str(input('sirul de caractere dat'))
print('sirul initial', S)
a=S.count('A')
b=S.replace('A', '*')
c=S.replace('B', '')
d=S.count('MA')
e=S.replace('MA', 'TA')
f=S.replace('TO', '')
g=S[::-1]
print('Numarul de aparitii ale caracterului A in sirul S:', a)
print('Sirul obtinut prin substituirea caracterului A prin caracterul *:', b)
print('Sirul obtinut prin radierea din sirul S a tuturor aparitiilor caracterului B:', c)
print('Numarul de aparitii ale silabei MA in sirul S:', d)
print('Sirul obtinut prin substituirea tuturor aparitiilor in sirul S a silabei MA prin silaba TA:', e)
print('Sirul obtinut prin radierea din sirul S a tuturor aparitiilor silabei TO:', f)
print('Scrierea inversa a sirului S:', g)
